name: on_night
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter





  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0 #could be 1.0.1 but needs Dart to be above 2.12.0 (current is 2.10.4)
  flutter_svg: ^0.19.1 # could be 0.19.2+1 but needs Flutter SDK above 1.24.0 (current is 1.22.4)
  webview_flutter: ^1.0.7
  curved_navigation_bar: ^0.3.3 #latest version
  flappy_search_bar: 1.7.2
  flutter_hooks: 0.15.0
  simple_animations: ^2.2.1
  google_fonts: ^1.1.0

  # The core of firebase fire plugin
  firebase_core: ^0.5.2+1

  # Dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^6.2.0

  # Dependencies for other Firebase products we want to use in OnNight.
  # Sudharsan is great and added GoogleMaps for Maria. 7/30/20
  firebase_auth: ^0.18.3+1
  cloud_firestore: ^0.14.3+1
  google_maps_flutter: ^1.0.6
  location: ^3.1.0
  rxdart: ^0.24.1
  rive: ^0.6.3
  flare_flutter: ^2.0.6

  # need for accessing location 12/2/2020
  permission: ^0.1.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon/icon_blue_corn.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true




  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/Calendar.svg
    - assets/cup.svg
    - assets/fracket.svg
    - assets/Map.svg
    - assets/Pine Tree.svg
    - assets/profile.svg
    - assets/SocialNetwork.svg
    - assets/DartmouthCommunity.svg
    - assets/DartmouthSocial.svg
    - assets/fluffy_fracket.svg
    - assets/settings_gear.svg
    - assets/cup_and_ball.svg
    - assets/google-logo.svg
    - assets/map_style.json
    - assets/on_night_background_10.png
    - assets/on_night_login_background.png
    - assets/login_background.png
    - assets/strawberry.jpg
    - assets/animations/
    - assets/maria_profile_pic.jpg
    - assets/images/icon/icon.png


  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: OnNightIcon
       fonts:
         - asset: icons/On_night_icons.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
