/// Flutter icons On_night_icons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  On_night_icons
///      fonts:
///       - asset: fonts/On_night_icons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class On_night_icons {
  On_night_icons._();

  static const _kFontFam = 'OnNightIcon';
  static const _kFontPkg = null;

  static const IconData fracket = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pine_tree = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData socialnetwork = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cup = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
